name: Shared - Assign GitHub Reviewer to Asana Task

on:
    pull_request:
        types: [review_requested]

jobs:

    create-asana-pr-subtask-if-needed:

        name: "Create the PR subtask in Asana"

        runs-on: ubuntu-latest

        steps:
        - name: Get Task ID
          id: get-task-id
          env:
            BODY: ${{ github.event.pull_request.body }}
          run: |
            task_id=$(grep -i "task/issue url.*https://app.asana.com/" <<< "$BODY" \
              | perl -pe 's|.*https://app.asana.com/0/[0-9]+/([0-9]+)(?:/f)?|\1|; \
                s|.*https://app.asana.com/1/[0-9]+(?:/[0-9a-z/]*)?/task/([0-9]+)(:?/[0-9a-z/]*)?(?:\?focus=true)?|\1|; \
                s|.*https://app.asana.com/1/[0-9]+/inbox/[0-9]+/item/([0-9]+)/story/([0-9]+)|\1|'
            )
            echo "task_id=${task_id//[^0-9]/}" >> $GITHUB_OUTPUT

        - name: Create or Update PR Subtask
          uses: duckduckgo/apple-toolbox/actions/asana-create-pr-subtask@main
          with:
            access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
            asana-task-id: ${{ steps.get-task-id.outputs.task_id }}
            github-reviewer-user: ${{ github.event.requested_reviewer.login }}
